### ISSUE TITLE
Please support decompress to STDOUT; or maybe a general UI overhaul?

### ISSUE THREAD

**Issue by romanrm** [dop251/spgz#1]
The usual convention is when specifying "-" as outfile, this would decompress to STDOUT.

Utils such as bzip2 and gzip also provide -c switch for STDOUT, but here it's already used for other purpose. On the other hand since this (amazingly ingenious) tool seems to be on the early stage of development and popularity, maybe it's still not too late to make the usage options as close as possible to standard gzip/bzip2? (see "gzip --help") Every new compression utility tends to go for that, such as xz/lzip/lzop/zstd/etc. Sure a few options from gzip are not possible or don't apply here, but the most basic ones still do.

**Comment by dop251** [comment]
spgz is not an equivalent of gzip or similar tools. Most of the usage scenarios would not make sense, consider for example "spgz /dev/sda1" or compressing to stdout.

As for decompressing to stdout, I'll add it.
