### ISSUE TITLE
how to build spgz?

### ISSUE THREAD

**Issue by Steve-Newcomb** [dop251/spgz#2]
Because of the help of a respondent to the "How to build this?" issue regarding diskrsync, I'm able to build diskrsync, but I have to use diskrsync in --no-compress mode because I have no idea how to build spgz.  If spgz doesn't work or can't be built, maybe diskrsync's readme.md file shouldn't mention it.  I'm attaching 2 files that show where I am with this.  install_diskrsync.txt is a bash script, and terminal_output.txt shows what happens when I run that script.  (I have almost no experience with Go.  I'm running on an up-to-date Debian Buster/Sid system.)
[install_diskrsync.txt](https://github.com/dop251/spgz/files/2719390/install_diskrsync.txt)
[terminal_output.txt](https://github.com/dop251/spgz/files/2719391/terminal_output.txt)

**Comment by dop251** [comment]
I have added installation instructions to diskrsync README, you can follow them, just replace diskrsync with spgz.

However, you don't need spgz binary to unpack compressed files, you can just as well use diskrsync:

```shell
diskrsync --no-compress compressed.spgz uncompressed_file
```
