### ISSUE TITLE
Can we mark /dev/nbd* device as readonly when using -buse-readonly?

### ISSUE THREAD

**Issue by zjuchenyuan** [dop251/spgz#3]
Currently, we need do this to mount an ext4 spgz image as readonly:

```
spgz -b imagefile -buse-readonly /dev/nbd0 -debug
mount -o ro,noload /dev/nbd0 /mnt
```

Reference: https://unix.stackexchange.com/questions/337638/mount-ext4-read-only

> If you make the device readonly first:
> blockdev --setro /dev/foo
> then the filesystem will be unable to write to it, so you don't need to know any special type-dependent filesystem options.

If this `blockdev` is automatically called, mount would be easier for user.

**Comment by dop251** [comment]
Yes!
